### ISSUE TITLE
pytorch ligtning error

### ISSUE THREAD

**Issue by overlord1647** [AlgoMole/MolCRAFT#7]
when i run 
(molcraft) [rahool@localhost MolCRAFT]$ python sample_for_pocket.py protein.pdb lig.sdf
i get the following error

Global seed set to 1234
tada.pdb lig.sdf
[DEBUG] get_dataloader
(29, 3) [47.314724 35.037724 12.047414]
protein feature dim: 27, ligand feature dim: 13
protein root: /home/rahool/MolCRAFT
GPU available: True (cuda), used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
/home/rahool/anaconda3/envs/molcraft/lib/python3.9/site-packages/pytorch_lightning/trainer/setup.py:175: PossibleUserWarning: GPU available but not used. Set `accelerator` and `devices` using `Trainer(accelerator='gpu', devices=4)`.
  rank_zero_warn(
Restoring states from the checkpoint path at ./checkpoints/last.ckpt
Loaded model weights from checkpoint at ./checkpoints/last.ckpt
/home/rahool/anaconda3/envs/molcraft/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:224: PossibleUserWarning: The dataloader, test_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 40 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
Testing: 0it [00:00, ?it/s]Traceback (most recent call last):
  File "/home/rahool/MolCRAFT/sample_for_pocket.py", line 269, in <module>
    call(protein_path, ligand_path)
  File "/home/rahool/MolCRAFT/sample_for_pocket.py", line 147, in call
    trainer.test(model, dataloaders=test_loader, ckpt_path=cfg.evaluation.ckpt_path)
  File "/home/rahool/anaconda3/envs/molcraft/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 780, in test
    return call._call_and_handle_interrupt(
  File "/home/rahool/anaconda3/envs/molcraft/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/rahool/anaconda3/envs/molcraft/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 829, in _test_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/rahool/anaconda3/envs/molcraft/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1098, in _run
    results = self._run_stage()
  File "/home/rahool/anaconda3/envs/molcraft/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1174, in _run_stage
    return self._run_evaluate()
  File "/home/rahool/anaconda3/envs/molcraft/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1214, in _run_evaluate
    eval_loop_results = self._evaluation_loop.run()
  File "/home/rahool/anaconda3/envs/molcraft/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/rahool/anaconda3/envs/molcraft/lib/python3.9/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 152, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/home/rahool/anaconda3/envs/molcraft/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/rahool/anaconda3/envs/molcraft/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 132, in advance
    self._on_evaluation_batch_start(**kwargs)
  File "/home/rahool/anaconda3/envs/molcraft/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 261, in _on_evaluation_batch_start
    self.trainer._call_callback_hooks(hook_name, *kwargs.values())
  File "/home/rahool/anaconda3/envs/molcraft/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1380, in _call_callback_hooks
    fn(self, self.lightning_module, *args, **kwargs)
TypeError: on_test_batch_start() takes 5 positional arguments but 6 were given
Testing: 0it [00:00, ?it/s]

**Comment by qky18** [comment]
Hi, it looks like you've installed the environment via conda, if I'm not mistaken.
I've checked the `environment.yml` file and found that the `pytorch_lightning` should be version 2.0.8, instead of 1.8.4. Hopefully this could address the problems.
If the error persists, can you describe the versions of relevant libraries?

**Comment by overlord1647** [comment]
works now. thanks.
